"""Rewrite .claude-plugin/marketplace.json and the README plugin list from plugins/*/.claude-plugin/plugin.json."""
import json
import pathlib
import re

MARKETPLACE = pathlib.Path(".claude-plugin/marketplace.json")
README = pathlib.Path("README.md")
SYNCED = ("description", "author", "license", "version")
BEGIN = "<!-- plugins:begin (generated by .github/scripts/sync_marketplace.py) -->"
END = "<!-- plugins:end -->"

market = json.loads(MARKETPLACE.read_text())
existing = {e["name"]: e for e in market["plugins"]}

plugins = []
for manifest_path in sorted(pathlib.Path("plugins").glob("*/.claude-plugin/plugin.json")):
    manifest = json.loads(manifest_path.read_text())
    name = manifest["name"]
    entry = existing.get(name, {"name": name})
    for key in SYNCED:
        if key in manifest:
            entry[key] = manifest[key]
    entry["source"] = f"./{manifest_path.parent.parent.as_posix()}"
    plugins.append(entry)

market["plugins"] = plugins
MARKETPLACE.write_text(json.dumps(market, indent=2, ensure_ascii=False) + "\n")


def license_line(entry):
    plugin_dir = pathlib.Path(entry["source"])
    license_name = entry.get("license", "see plugin")
    license_file = plugin_dir / "LICENSE"
    if license_file.is_file():
        return f"License: [{license_name}]({license_file.as_posix()})"
    return f"License: {license_name}"


sections = []
for entry in plugins:
    sections.append(
        f"### {entry['name']} \n\n"
        f"**Version:** {entry.get('version', 'unversioned')}  \n"
        f"{entry.get('description', '')}  \n"
        f"{license_line(entry)}\n"
    )
block = f"{BEGIN}\n\n" + "\n".join(sections) + f"\n{END}"

if README.is_file():
    text = README.read_text()
else:
    text = f"# {market['name']}\n\n## Plugins\n\n{BEGIN}\n{END}\n"
if BEGIN not in text:
    text = text.rstrip("\n") + f"\n\n## Plugins\n\n{BEGIN}\n{END}\n"
text = re.sub(re.escape(BEGIN) + ".*?" + re.escape(END), lambda _: block, text, flags=re.S)
README.write_text(text)
